apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app:  httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: alpine.base
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
        stdin: true
        tty: true
        ports:
        - name: http
          containerPort: 8888
