apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app:  httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: alpine.base
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 50m
        stdin: true
        tty: true
        args:
        - /bin/sh
        - -c
        - sleep 20; timeout 20s nc -l localhost -p 9999
        ports:
        - name: http
          containerPort: 8888
        - name: readiness
          containerPort: 9999
        readinessProbe:
          tcpSocket:
            port: 9999
          initialDelaySeconds: 5
          periodSeconds: 5

 



